version: 2
build:
  binary: ciferd
  ldflags:
  - -X main.Env=prod
  - -X main.Version=0.25.1
  proto:
    path: proto
    third_party_paths:
    - third_party/proto
    - proto_vendor
client:
  typescript:
    path: ts-client
  composables:
    path: vue/src/composables
  openapi:
    path: docs/static/openapi.yml
